### ISSUE TITLE
micromatch dependency is vulnerable

### ISSUE THREAD

**Issue by olgapavlova** [eduhund/figma-plugin-template#2]
After dependency installation, ```npm audit fix``` says:
![Снимок экрана 2024-09-22 в 19 53 35](https://github.com/user-attachments/assets/a546c1f6-9443-465c-b488-ce5b6ad4ac1c)

**Comment by roman-nebel** [comment]
@olgapavlova Thanks for reaching out!

Unfortunately, this is a dependency of linter (or some other module). We can't fully keep their dependencies up-to-date. But we will try to fix these warnings locally in this repo.

**Comment by roman-nebel** [comment]
@olgapavlova We updated the version of lint-staged module and fixed the vulnerabilities. Please, pull the changes and try to re-install the dependencies.
